<a href="https://colab.research.google.com/github/sreehithreddy0202/pytorch_learning/blob/main/04_training_pipeline_using_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[ 1.60428583, -0.07778808,  1.61395739, ...,  1.30095279,
         0.09156457,  0.82903608],
       [-1.57418298, -1.41452532, -1.53739935, ..., -0.43769832,
         0.11548984,  1.13469763],
       [-0.44914598, -0.81529828, -0.35874065, ...,  0.93282946,
         1.71369823,  2.19715756],
       ...,
       [ 1.30265178, -0.39583935,  1.26927117, ...,  0.81268879,
        -0.63895383,  0.56532807],
       [-0.60866398, -1.05729382, -0.54621632, ..., -0.81814377,
        -0.29283485,  1.06386696],
       [-0.72177675,  1.08148577, -0.69712163, ..., -0.26195408,
        -1.27377113,  0.17684913]])

In [9]:
y_train

300    M
525    B
5      M
75     M
6      M
      ..
88     B
43     M
498    M
145    B
559    B
Name: diagnosis, Length: 455, dtype: object

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train

array([1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0])

In [12]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [13]:
import torch.nn as nn


class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [22]:
learning_rate = 0.1
epochs = 250

In [23]:
loss_function = nn.BCELoss()

In [24]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))

  # clear gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.9055567383766174
Epoch: 2, Loss: 0.24506662786006927
Epoch: 3, Loss: 0.2035241425037384
Epoch: 4, Loss: 0.17898119986057281
Epoch: 5, Loss: 0.16264505684375763
Epoch: 6, Loss: 0.15084804594516754
Epoch: 7, Loss: 0.1418333351612091
Epoch: 8, Loss: 0.13465921580791473
Epoch: 9, Loss: 0.12877480685710907
Epoch: 10, Loss: 0.12383492290973663
Epoch: 11, Loss: 0.1196112111210823
Epoch: 12, Loss: 0.11594579368829727
Epoch: 13, Loss: 0.11272558569908142
Epoch: 14, Loss: 0.1098671406507492
Epoch: 15, Loss: 0.10730738937854767
Epoch: 16, Loss: 0.10499764233827591
Epoch: 17, Loss: 0.10289958864450455
Epoch: 18, Loss: 0.100982666015625
Epoch: 19, Loss: 0.09922216087579727
Epoch: 20, Loss: 0.09759778529405594
Epoch: 21, Loss: 0.09609278291463852
Epoch: 22, Loss: 0.0946931391954422
Epoch: 23, Loss: 0.09338699281215668
Epoch: 24, Loss: 0.09216431528329849
Epoch: 25, Loss: 0.09101652354001999
Epoch: 26, Loss: 0.08993616700172424
Epoch: 27, Loss: 0.0889168530702591
Epoch: 28, Loss: 0.08795297145843506
Epoch: 29, Loss: 0.08703959733247757
Epoch: 30, Loss: 0.0861724317073822
Epoch: 31, Loss: 0.08534763753414154
Epoch: 32, Loss: 0.08456181734800339
Epoch: 33, Loss: 0.08381196856498718
Epoch: 34, Loss: 0.08309536427259445
Epoch: 35, Loss: 0.08240959048271179
Epoch: 36, Loss: 0.08175244927406311
Epoch: 37, Loss: 0.08112197369337082
Epoch: 38, Loss: 0.08051636070013046
Epoch: 39, Loss: 0.07993398606777191
Epoch: 40, Loss: 0.07937336713075638
Epoch: 41, Loss: 0.07883317023515701
Epoch: 42, Loss: 0.07831213623285294
Epoch: 43, Loss: 0.07780914008617401
Epoch: 44, Loss: 0.07732313871383667
Epoch: 45, Loss: 0.07685317099094391
Epoch: 46, Loss: 0.07639836519956589
Epoch: 47, Loss: 0.07595787942409515
Epoch: 48, Loss: 0.07553096115589142
Epoch: 49, Loss: 0.07511693239212036
Epoch: 50, Loss: 0.07471510767936707
Epoch: 51, Loss: 0.07432490587234497
Epoch: 52, Loss: 0.07394574582576752
Epoch: 53, Loss: 0.07357710599899292
Epoch: 54, Loss: 0.07321850210428238
Epoch: 55, Loss: 0.07286946475505829
Epoch: 56, Loss: 0.07252953201532364
Epoch: 57, Loss: 0.07219836860895157
Epoch: 58, Loss: 0.07187554985284805
Epoch: 59, Loss: 0.07156071811914444
Epoch: 60, Loss: 0.07125356793403625
Epoch: 61, Loss: 0.07095374166965485
Epoch: 62, Loss: 0.07066096365451813
Epoch: 63, Loss: 0.07037495076656342
Epoch: 64, Loss: 0.07009544223546982
Epoch: 65, Loss: 0.06982218474149704
Epoch: 66, Loss: 0.06955493241548538
Epoch: 67, Loss: 0.06929346919059753
Epoch: 68, Loss: 0.06903757899999619
Epoch: 69, Loss: 0.06878706067800522
Epoch: 70, Loss: 0.06854173541069031
Epoch: 71, Loss: 0.06830139458179474
Epoch: 72, Loss: 0.06806588172912598
Epoch: 73, Loss: 0.06783502548933029
Epoch: 74, Loss: 0.06760866940021515
Epoch: 75, Loss: 0.0673866719007492
Epoch: 76, Loss: 0.06716887652873993
Epoch: 77, Loss: 0.06695517152547836
Epoch: 78, Loss: 0.06674540042877197
Epoch: 79, Loss: 0.0665394514799118
Epoch: 80, Loss: 0.06633719801902771
Epoch: 81, Loss: 0.06613854318857193
Epoch: 82, Loss: 0.06594336032867432
Epoch: 83, Loss: 0.0657515600323677
Epoch: 84, Loss: 0.06556303054094315
Epoch: 85, Loss: 0.06537768989801407
Epoch: 86, Loss: 0.06519542634487152
Epoch: 87, Loss: 0.06501618027687073
Epoch: 88, Loss: 0.06483984738588333
Epoch: 89, Loss: 0.06466634571552277
Epoch: 90, Loss: 0.06449560075998306
Epoch: 91, Loss: 0.06432755291461945
Epoch: 92, Loss: 0.06416211277246475
Epoch: 93, Loss: 0.0639992207288742
Epoch: 94, Loss: 0.06383878737688065
Epoch: 95, Loss: 0.06368079036474228
Epoch: 96, Loss: 0.06352512538433075
Epoch: 97, Loss: 0.06337177008390427
Epoch: 98, Loss: 0.06322063505649567
Epoch: 99, Loss: 0.06307169049978256
Epoch: 100, Loss: 0.06292486935853958
Epoch: 101, Loss: 0.06278011947870255
Epoch: 102, Loss: 0.06263739615678787
Epoch: 103, Loss: 0.062496647238731384
Epoch: 104, Loss: 0.0623578317463398
Epoch: 105, Loss: 0.06222090497612953
Epoch: 106, Loss: 0.06208581477403641
Epoch: 107, Loss: 0.06195252761244774
Epoch: 108, Loss: 0.06182100251317024
Epoch: 109, Loss: 0.06169119477272034
Epoch: 110, Loss: 0.06156306341290474
Epoch: 111, Loss: 0.06143658235669136
Epoch: 112, Loss: 0.061311714351177216
Epoch: 113, Loss: 0.06118842586874962
Epoch: 114, Loss: 0.06106667220592499
Epoch: 115, Loss: 0.060946427285671234
Epoch: 116, Loss: 0.06082766875624657
Epoch: 117, Loss: 0.060710348188877106
Epoch: 118, Loss: 0.060594454407691956
Epoch: 119, Loss: 0.06047993153333664
Epoch: 120, Loss: 0.060366783291101456
Epoch: 121, Loss: 0.06025496497750282
Epoch: 122, Loss: 0.06014445424079895
Epoch: 123, Loss: 0.06003522500395775
Epoch: 124, Loss: 0.05992725118994713
Epoch: 125, Loss: 0.0598205141723156
Epoch: 126, Loss: 0.05971498414874077
Epoch: 127, Loss: 0.05961063876748085
Epoch: 128, Loss: 0.05950745567679405
Epoch: 129, Loss: 0.05940541252493858
Epoch: 130, Loss: 0.05930449441075325
Epoch: 131, Loss: 0.05920467898249626
Epoch: 132, Loss: 0.05910594388842583
Epoch: 133, Loss: 0.05900825560092926
Epoch: 134, Loss: 0.05891162157058716
Epoch: 135, Loss: 0.058816008269786835
Epoch: 136, Loss: 0.058721400797367096
Epoch: 137, Loss: 0.05862777307629585
Epoch: 138, Loss: 0.058535125106573105
Epoch: 139, Loss: 0.058443427085876465
Epoch: 140, Loss: 0.05835266038775444
Epoch: 141, Loss: 0.05826282128691673
Epoch: 142, Loss: 0.05817388743162155
Epoch: 143, Loss: 0.058085840195417404
Epoch: 144, Loss: 0.05799867957830429
Epoch: 145, Loss: 0.057912372052669525
Epoch: 146, Loss: 0.05782690644264221
Epoch: 147, Loss: 0.05774229019880295
Epoch: 148, Loss: 0.05765847861766815
Epoch: 149, Loss: 0.05757547914981842
Epoch: 150, Loss: 0.05749326944351196
Epoch: 151, Loss: 0.05741185322403908
Epoch: 152, Loss: 0.05733119323849678
Epoch: 153, Loss: 0.057251300662755966
Epoch: 154, Loss: 0.05717214196920395
Epoch: 155, Loss: 0.057093728333711624
Epoch: 156, Loss: 0.057016026228666306
Epoch: 157, Loss: 0.05693904310464859
Epoch: 158, Loss: 0.056862760335206985
Epoch: 159, Loss: 0.056787166744470596
Epoch: 160, Loss: 0.056712254881858826
Epoch: 161, Loss: 0.05663801729679108
Epoch: 162, Loss: 0.05656442791223526
Epoch: 163, Loss: 0.05649149790406227
Epoch: 164, Loss: 0.05641920864582062
Epoch: 165, Loss: 0.05634754151105881
Epoch: 166, Loss: 0.056276511400938034
Epoch: 167, Loss: 0.05620608851313591
Epoch: 168, Loss: 0.056136276572942734
Epoch: 169, Loss: 0.056067053228616714
Epoch: 170, Loss: 0.05599842593073845
Epoch: 171, Loss: 0.05593036860227585
Epoch: 172, Loss: 0.05586288869380951
Epoch: 173, Loss: 0.055795975029468536
Epoch: 174, Loss: 0.055729616433382034
Epoch: 175, Loss: 0.055663805454969406
Epoch: 176, Loss: 0.05559853836894035
Epoch: 177, Loss: 0.05553380399942398
Epoch: 178, Loss: 0.05546959862112999
Epoch: 179, Loss: 0.055405911058187485
Epoch: 180, Loss: 0.05534273758530617
Epoch: 181, Loss: 0.05528007447719574
Epoch: 182, Loss: 0.05521790683269501
Epoch: 183, Loss: 0.05515623092651367
Epoch: 184, Loss: 0.05509504675865173
Epoch: 185, Loss: 0.055034339427948
Epoch: 186, Loss: 0.05497410520911217
Epoch: 187, Loss: 0.05491434410214424
Epoch: 188, Loss: 0.05485505238175392
Epoch: 189, Loss: 0.05479620769619942
Epoch: 190, Loss: 0.05473780632019043
Epoch: 191, Loss: 0.05467986315488815
Epoch: 192, Loss: 0.054622359573841095
Epoch: 193, Loss: 0.05456528812646866
Epoch: 194, Loss: 0.054508645087480545
Epoch: 195, Loss: 0.054452430456876755
Epoch: 196, Loss: 0.05439663305878639
Epoch: 197, Loss: 0.05434124544262886
Epoch: 198, Loss: 0.05428626760840416
Epoch: 199, Loss: 0.05423169583082199
Epoch: 200, Loss: 0.05417751520872116
Epoch: 201, Loss: 0.054123736917972565
Epoch: 202, Loss: 0.05407034978270531
Epoch: 203, Loss: 0.05401734262704849
Epoch: 204, Loss: 0.053964726626873016
Epoch: 205, Loss: 0.05391247570514679
Epoch: 206, Loss: 0.05386060103774071
Epoch: 207, Loss: 0.053809087723493576
Epoch: 208, Loss: 0.05375794321298599
Epoch: 209, Loss: 0.05370715633034706
Epoch: 210, Loss: 0.05365673080086708
Epoch: 211, Loss: 0.05360664799809456
Epoch: 212, Loss: 0.05355691909790039
Epoch: 213, Loss: 0.053507525473833084
Epoch: 214, Loss: 0.05345848575234413
Epoch: 215, Loss: 0.053409770131111145
Epoch: 216, Loss: 0.05336138978600502
Epoch: 217, Loss: 0.05331333726644516
Epoch: 218, Loss: 0.05326560139656067
Epoch: 219, Loss: 0.05321820452809334
Epoch: 220, Loss: 0.05317111313343048
Epoch: 221, Loss: 0.05312433838844299
Epoch: 222, Loss: 0.053077876567840576
Epoch: 223, Loss: 0.053031716495752335
Epoch: 224, Loss: 0.052985869348049164
Epoch: 225, Loss: 0.05294031277298927
Epoch: 226, Loss: 0.052895065397024155
Epoch: 227, Loss: 0.052850108593702316
Epoch: 228, Loss: 0.05280543863773346
Epoch: 229, Loss: 0.05276105925440788
Epoch: 230, Loss: 0.05271696671843529
Epoch: 231, Loss: 0.05267316475510597
Epoch: 232, Loss: 0.05262962356209755
Epoch: 233, Loss: 0.052586376667022705
Epoch: 234, Loss: 0.05254339799284935
Epoch: 235, Loss: 0.05250069499015808
Epoch: 236, Loss: 0.052458252757787704
Epoch: 237, Loss: 0.052416082471609116
Epoch: 238, Loss: 0.05237417295575142
Epoch: 239, Loss: 0.052332524210214615
Epoch: 240, Loss: 0.052291132509708405
Epoch: 241, Loss: 0.05224999785423279
Epoch: 242, Loss: 0.05220911651849747
Epoch: 243, Loss: 0.052168481051921844
Epoch: 244, Loss: 0.05212809890508652
Epoch: 245, Loss: 0.05208795145153999
Epoch: 246, Loss: 0.052048057317733765
Epoch: 247, Loss: 0.052008405327796936
Epoch: 248, Loss: 0.05196898430585861
Epoch: 249, Loss: 0.05192979797720909
Epoch: 250, Loss: 0.05189085751771927

In [25]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5138503909111023